[program:kyc-customer-application]
command=node dist/main.js --env-file .env.prod
directory=/opt/kyc/apps/kyc-customer-application
user=kyc_user
group=kyc_user
priority=1000
autostart=true
autorestart=true
startretries=3
startsecs=3
stopsignal=INT
numprocs=1
process_name=%(program_name)s
stdout_logfile=/opt/kyc/logs/supervisor/%(program_name)s_stdout.log