[program:kyc-gateway]
command=java -Xms128m -Dspring.profiles.active=prod -Dserver.port=100%(process_num)02d -Dinstance=%(process_num)02d -Dspring.config.additional-location=/opt/kyc/kyc-config-files/,/opt/kyc/apps/kyc-gateway/ -jar kyc-gateway.jar
directory=/opt/kyc/apps/kyc-gateway
user=kyc_user
group=kyc_user
autostart=true
autorestart=true
startretries=3
startsecs=3
stopsignal=INT
numprocs=2
process_name=%(program_name)s-%(process_num)02d
stdout_logfile=/opt/kyc/logs/supervisor/%(program_name)s-%(process_num)02d_stdout.log